// //json created using order matix and UI to rerender UI based on user selection
// import 'package:acml/src/config/app_config.dart';

// Map<String, Map<String, dynamic>> json = {
//   "NSE": {
//     "instrument": [
//       "STK",
//       "ETF",
//     ],
//     "productTypes": [
//       "Regular",
//       if (Featureflag.coverOder) "Cover Order",
//       if (Featureflag.bracketOder) "Bracket Order",
//     ],
//     "Invest": {
//       "orderTypes": [
//         "Market",
//         "Limit",
//         "SL",
//         "SL-M",
//       ],
//       "Market": {
//         "qty": true,
//         "customPrice": false,
//         "triggerPrice": false,
//         "stopLossTrigger": false,
//         "stopLossPrice": false,
//         "targetPrice": false,
//         "trailingStopLoss": false,
//         "validity": ["DAY", "IOC", if (Featureflag.gTD) "GTD"],
//         "Amo": true,
//         "disQty": true,
//       },
//       "Limit": {
//         "qty": true,
//         "customPrice": true,
//         "triggerPrice": false,
//         "stopLossTrigger": false,
//         "stopLossPrice": false,
//         "targetPrice": false,
//         "trailingStopLoss": false,
//         "validity": [
//           "DAY",
//           "IOC",
//           if (Featureflag.gTD) "GTD",
//         ],
//         "Amo": true,
//         "disQty": true,
//       },
//       "SL": {
//         "qty": true,
//         "customPrice": true,
//         "triggerPrice": true,
//         "stopLossTrigger": false,
//         "stopLossPrice": false,
//         "targetPrice": false,
//         "trailingStopLoss": false,
//         "validity": [
//           "DAY",
//           if (Featureflag.gTD) "GTD",
//         ],
//         "Amo": true,
//         "disQty": true,
//       },
//       "SL-M": {
//         "qty": true,
//         "customPrice": false,
//         "triggerPrice": true,
//         "stopLossTrigger": false,
//         "stopLossPrice": false,
//         "targetPrice": false,
//         "trailingStopLoss": false,
//         "validity": ["DAY", if (Featureflag.gTD) "GTD"],
//         "Amo": true,
//         "disQty": true,
//       },
//     },
//     "Trade": {
//       "orderTypes": [
//         "Market",
//         "Limit",
//         "SL",
//         "SL-M",
//       ],
//       "Market": {
//         "qty": true,
//         "customPrice": false,
//         "triggerPrice": false,
//         "stopLossTrigger": false,
//         "stopLossPrice": false,
//         "targetPrice": false,
//         "trailingStopLoss": false,
//         "validity": ["DAY", "IOC", if (Featureflag.gTD) "GTD"],
//         "Amo": true,
//         "disQty": true,
//       },
//       "Limit": {
//         "qty": true,
//         "customPrice": true,
//         "triggerPrice": false,
//         "stopLossTrigger": false,
//         "stopLossPrice": false,
//         "targetPrice": false,
//         "trailingStopLoss": false,
//         "validity": ["DAY", "IOC", if (Featureflag.gTD) "GTD"],
//         "Amo": true,
//         "disQty": true,
//       },
//       "SL": {
//         "qty": true,
//         "customPrice": true,
//         "triggerPrice": true,
//         "stopLossTrigger": false,
//         "stopLossPrice": false,
//         "targetPrice": false,
//         "trailingStopLoss": false,
//         "validity": ["DAY", if (Featureflag.gTD) "GTD"],
//         "Amo": true,
//         "disQty": true,
//       },
//       "SL-M": {
//         "qty": true,
//         "customPrice": false,
//         "triggerPrice": true,
//         "stopLossTrigger": false,
//         "stopLossPrice": false,
//         "targetPrice": false,
//         "trailingStopLoss": false,
//         "validity": ["DAY", if (Featureflag.gTD) "GTD"],
//         "Amo": true,
//         "disQty": true,
//       },
//     },
//     "CoverOrder": {
//       "orderTypes": [
//         "Market",
//         "Limit",
//         "SL",
//         "SL-M",
//       ],
//       "SL": {
//         "qty": true,
//         "customPrice": true,
//         "triggerPrice": false,
//         "stopLossTrigger": true,
//         "stopLossPrice": false,
//         "targetPrice": false,
//         "trailingStopLoss": false,
//         "validity": [
//           "DAY",
//         ],
//         "Amo": false,
//         "disQty": false,
//       },
//       "SL-M": {
//         "qty": true,
//         "customPrice": false,
//         "triggerPrice": false,
//         "stopLossTrigger": true,
//         "stopLossPrice": false,
//         "targetPrice": false,
//         "trailingStopLoss": false,
//         "validity": [
//           "DAY",
//         ],
//         "Amo": false,
//         "disQty": false,
//       },
//       "Market": {
//         "qty": true,
//         "customPrice": false,
//         "triggerPrice": false,
//         "stopLossTrigger": true,
//         "stopLossPrice": false,
//         "targetPrice": false,
//         "trailingStopLoss": false,
//         "validity": [
//           "DAY",
//         ],
//         "Amo": false,
//         "disQty": false,
//       },
//       "Limit": {
//         "qty": true,
//         "customPrice": true,
//         "triggerPrice": false,
//         "stopLossTrigger": true,
//         "stopLossPrice": false,
//         "targetPrice": false,
//         "trailingStopLoss": false,
//         "validity": [
//           "DAY",
//         ],
//         "Amo": false,
//         "disQty": false,
//       },
//     },
//     "BracketOrder": {
//       "orderTypes": [
//         "Limit",
//         "SL",
//       ],
//       "Limit": {
//         "qty": true,
//         "customPrice": true,
//         "triggerPrice": false,
//         "stopLossTrigger": false,
//         "stopLossPrice": true,
//         "targetPrice": true,
//         "trailingStopLoss": true,
//         "validity": [
//           "DAY",
//         ],
//         "Amo": false,
//         "disQty": false,
//       },
//       "SL": {
//         "qty": true,
//         "customPrice": true,
//         "triggerPrice": true,
//         "stopLossTrigger": false,
//         "stopLossPrice": true,
//         "targetPrice": true,
//         "trailingStopLoss": true,
//         "validity": [
//           "DAY",
//         ],
//         "Amo": false,
//         "disQty": false,
//       },
//     },
//   },
//   "BSE": {
//     "instrument": [
//       "STK",
//       "ETF",
//     ],
//     "productTypes": [
//       "Regular",
//       if (Featureflag.coverOder) "Cover Order",
//       if (Featureflag.bracketOder) "Bracket Order",
//     ],
//     "Invest": {
//       "orderTypes": [
//         "Market",
//         "Limit",
//         "SL",
//         "SL-M",
//       ],
//       "Market": {
//         "qty": true,
//         "customPrice": false,
//         "triggerPrice": false,
//         "stopLossTrigger": false,
//         "stopLossPrice": false,
//         "targetPrice": false,
//         "trailingStopLoss": false,
//         "validity": ["DAY", "IOC", if (Featureflag.gTD) "GTD"],
//         "Amo": true,
//         "disQty": true,
//       },
//       "Limit": {
//         "qty": true,
//         "customPrice": true,
//         "triggerPrice": false,
//         "stopLossTrigger": false,
//         "stopLossPrice": false,
//         "targetPrice": false,
//         "trailingStopLoss": false,
//         "validity": [
//           "DAY",
//           "IOC",
//           if (Featureflag.gTD) "GTD",
//         ],
//         "Amo": true,
//         "disQty": true,
//       },
//       "SL": {
//         "qty": true,
//         "customPrice": true,
//         "triggerPrice": true,
//         "stopLossTrigger": false,
//         "stopLossPrice": false,
//         "targetPrice": false,
//         "trailingStopLoss": false,
//         "validity": [
//           "DAY",
//           if (Featureflag.gTD) "GTD",
//         ],
//         "Amo": true,
//         "disQty": true,
//       },
//       "SL-M": {
//         "qty": true,
//         "customPrice": false,
//         "triggerPrice": true,
//         "stopLossTrigger": false,
//         "stopLossPrice": false,
//         "targetPrice": false,
//         "trailingStopLoss": false,
//         "validity": ["DAY", if (Featureflag.gTD) "GTD"],
//         "Amo": true,
//         "disQty": true,
//       },
//     },
//     "Trade": {
//       "orderTypes": [
//         "Market",
//         "Limit",
//         "SL",
//         "SL-M",
//       ],
//       "Market": {
//         "qty": true,
//         "customPrice": false,
//         "triggerPrice": false,
//         "stopLossTrigger": false,
//         "stopLossPrice": false,
//         "targetPrice": false,
//         "trailingStopLoss": false,
//         "validity": ["DAY", "IOC", if (Featureflag.gTD) "GTD"],
//         "Amo": true,
//         "disQty": true,
//       },
//       "Limit": {
//         "qty": true,
//         "customPrice": true,
//         "triggerPrice": false,
//         "stopLossTrigger": false,
//         "stopLossPrice": false,
//         "targetPrice": false,
//         "trailingStopLoss": false,
//         "validity": ["DAY", "IOC", if (Featureflag.gTD) "GTD"],
//         "Amo": true,
//         "disQty": true,
//       },
//       "SL": {
//         "qty": true,
//         "customPrice": true,
//         "triggerPrice": true,
//         "stopLossTrigger": false,
//         "stopLossPrice": false,
//         "targetPrice": false,
//         "trailingStopLoss": false,
//         "validity": ["DAY", if (Featureflag.gTD) "GTD"],
//         "Amo": true,
//         "disQty": true,
//       },
//       "SL-M": {
//         "qty": true,
//         "customPrice": false,
//         "triggerPrice": true,
//         "stopLossTrigger": false,
//         "stopLossPrice": false,
//         "targetPrice": false,
//         "trailingStopLoss": false,
//         "validity": ["DAY", if (Featureflag.gTD) "GTD"],
//         "Amo": true,
//         "disQty": true,
//       },
//     },
//     "CoverOrder": {
//       "orderTypes": [
//         "Market",
//         "Limit",
//         "SL",
//         "SL-M",
//       ],
//       "SL": {
//         "qty": true,
//         "customPrice": true,
//         "triggerPrice": true,
//         "stopLossTrigger": false,
//         "stopLossPrice": false,
//         "targetPrice": false,
//         "trailingStopLoss": false,
//         "validity": [
//           "DAY",
//         ],
//         "Amo": true,
//         "disQty": true,
//       },
//       "SL-M": {
//         "qty": true,
//         "customPrice": false,
//         "triggerPrice": true,
//         "stopLossTrigger": false,
//         "stopLossPrice": false,
//         "targetPrice": false,
//         "trailingStopLoss": false,
//         "validity": [
//           "DAY",
//         ],
//         "Amo": true,
//         "disQty": true,
//       },
//       "Market": {
//         "qty": true,
//         "customPrice": false,
//         "triggerPrice": false,
//         "stopLossTrigger": true,
//         "stopLossPrice": false,
//         "targetPrice": false,
//         "trailingStopLoss": false,
//         "validity": [
//           "DAY",
//         ],
//         "Amo": false,
//         "disQty": false,
//       },
//       "Limit": {
//         "qty": true,
//         "customPrice": true,
//         "triggerPrice": false,
//         "stopLossTrigger": true,
//         "stopLossPrice": false,
//         "targetPrice": false,
//         "trailingStopLoss": false,
//         "validity": [
//           "DAY",
//         ],
//         "Amo": false,
//         "disQty": false,
//       },
//     },
//     "BracketOrder": {
//       "orderTypes": [
//         "Limit",
//         "SL",
//       ],
//       "Limit": {
//         "qty": true,
//         "customPrice": true,
//         "triggerPrice": false,
//         "stopLossTrigger": false,
//         "stopLossPrice": true,
//         "targetPrice": true,
//         "trailingStopLoss": true,
//         "validity": [
//           "DAY",
//         ],
//         "Amo": false,
//         "disQty": false,
//       },
//       "SL": {
//         "qty": true,
//         "customPrice": true,
//         "triggerPrice": true,
//         "stopLossTrigger": false,
//         "stopLossPrice": true,
//         "targetPrice": true,
//         "trailingStopLoss": true,
//         "validity": [
//           "DAY",
//         ],
//         "Amo": false,
//         "disQty": false,
//       },
//     },
//   },
//   "NFO": {
//     "instrument": [
//       "FUTSTK",
//       "OPTSTK",
//       "FUTIDX",
//       "OPTIDX",
//     ],
//     "productTypes": [
//       "Regular",
//       if (Featureflag.coverOder) "Cover Order",
//       if (Featureflag.bracketOder) "Bracket Order",
//     ],
//     "Invest": {
//       "orderTypes": [
//         "Market",
//         "Limit",
//         "SL",
//         "SL-M",
//       ],
//       "Market": {
//         "qty": true,
//         "customPrice": false,
//         "triggerPrice": false,
//         "stopLossTrigger": false,
//         "stopLossPrice": false,
//         "targetPrice": false,
//         "trailingStopLoss": false,
//         "validity": ["DAY", "IOC", if (Featureflag.gTD) "GTD"],
//         "Amo": true,
//         "disQty": true,
//       },
//       "Limit": {
//         "qty": true,
//         "customPrice": true,
//         "triggerPrice": false,
//         "stopLossTrigger": false,
//         "stopLossPrice": false,
//         "targetPrice": false,
//         "trailingStopLoss": false,
//         "validity": ["DAY", "IOC", if (Featureflag.gTD) "GTD"],
//         "Amo": true,
//         "disQty": true,
//       },
//       "SL": {
//         "qty": true,
//         "customPrice": true,
//         "triggerPrice": true,
//         "stopLossTrigger": false,
//         "stopLossPrice": false,
//         "targetPrice": false,
//         "trailingStopLoss": false,
//         "validity": ["DAY", if (Featureflag.gTD) "GTD"],
//         "Amo": true,
//         "disQty": true,
//       },
//       "SL-M": {
//         "qty": true,
//         "customPrice": false,
//         "triggerPrice": true,
//         "stopLossTrigger": false,
//         "stopLossPrice": false,
//         "targetPrice": false,
//         "trailingStopLoss": false,
//         "validity": ["DAY", if (Featureflag.gTD) "GTD"],
//         "Amo": true,
//         "disQty": true,
//       },
//     },
//     "Trade": {
//       "orderTypes": [
//         "Market",
//         "Limit",
//         "SL",
//         "SL-M",
//       ],
//       "Market": {
//         "qty": true,
//         "customPrice": false,
//         "triggerPrice": false,
//         "stopLossTrigger": false,
//         "stopLossPrice": false,
//         "targetPrice": false,
//         "trailingStopLoss": false,
//         "validity": ["DAY", "IOC", if (Featureflag.gTD) "GTD"],
//         "Amo": true,
//         "disQty": true,
//       },
//       "Limit": {
//         "qty": true,
//         "customPrice": true,
//         "triggerPrice": false,
//         "stopLossTrigger": false,
//         "stopLossPrice": false,
//         "targetPrice": false,
//         "trailingStopLoss": false,
//         "validity": ["DAY", "IOC", if (Featureflag.gTD) "GTD"],
//         "Amo": true,
//         "disQty": true,
//       },
//       "SL": {
//         "qty": true,
//         "customPrice": true,
//         "triggerPrice": true,
//         "stopLossTrigger": false,
//         "stopLossPrice": false,
//         "targetPrice": false,
//         "trailingStopLoss": false,
//         "validity": ["DAY", if (Featureflag.gTD) "GTD"],
//         "Amo": true,
//         "disQty": true,
//       },
//       "SL-M": {
//         "qty": true,
//         "customPrice": false,
//         "triggerPrice": true,
//         "stopLossTrigger": false,
//         "stopLossPrice": false,
//         "targetPrice": false,
//         "trailingStopLoss": false,
//         "validity": ["DAY", if (Featureflag.gTD) "GTD"],
//         "Amo": true,
//         "disQty": true,
//       },
//     },
//     "CoverOrder": {
//       "orderTypes": [
//         "Market",
//         "Limit",
//         "SL",
//         "SL-M",
//       ],
//       "SL": {
//         "qty": true,
//         "customPrice": true,
//         "triggerPrice": true,
//         "stopLossTrigger": false,
//         "stopLossPrice": false,
//         "targetPrice": false,
//         "trailingStopLoss": false,
//         "validity": [
//           "DAY",
//         ],
//         "Amo": true,
//         "disQty": true,
//       },
//       "SL-M": {
//         "qty": true,
//         "customPrice": false,
//         "triggerPrice": true,
//         "stopLossTrigger": false,
//         "stopLossPrice": false,
//         "targetPrice": false,
//         "trailingStopLoss": false,
//         "validity": [
//           "DAY",
//         ],
//         "Amo": true,
//         "disQty": true,
//       },
//       "Market": {
//         "qty": true,
//         "customPrice": false,
//         "triggerPrice": false,
//         "stopLossTrigger": true,
//         "stopLossPrice": false,
//         "targetPrice": false,
//         "trailingStopLoss": false,
//         "validity": [
//           "DAY",
//         ],
//         "Amo": false,
//         "disQty": false,
//       },
//       "Limit": {
//         "qty": true,
//         "customPrice": true,
//         "triggerPrice": false,
//         "stopLossTrigger": true,
//         "stopLossPrice": false,
//         "targetPrice": false,
//         "trailingStopLoss": false,
//         "validity": [
//           "DAY",
//         ],
//         "Amo": false,
//         "disQty": false,
//       },
//     },
//     "BracketOrder": {
//       "orderTypes": [
//         "Limit",
//         "SL",
//       ],
//       "Limit": {
//         "qty": true,
//         "customPrice": true,
//         "triggerPrice": false,
//         "stopLossTrigger": false,
//         "stopLossPrice": true,
//         "targetPrice": true,
//         "trailingStopLoss": true,
//         "validity": [
//           "DAY",
//         ],
//         "Amo": false,
//         "disQty": false,
//       },
//       "SL": {
//         "qty": true,
//         "customPrice": true,
//         "triggerPrice": true,
//         "stopLossTrigger": false,
//         "stopLossPrice": true,
//         "targetPrice": true,
//         "trailingStopLoss": true,
//         "validity": [
//           "DAY",
//         ],
//         "Amo": false,
//         "disQty": false,
//       },
//     },
//   },
//   "BFO": {
//     "instrument": [
//       "FUTSTK",
//       "OPTSTK",
//       "FUTIDX",
//       "OPTIDX",
//     ],
//     "productTypes": [
//       "Regular",
//       if (Featureflag.coverOder) "Cover Order",
//       if (Featureflag.bracketOder) "Bracket Order",
//     ],
//     "Invest": {
//       "orderTypes": [
//         "Market",
//         "Limit",
//         "SL",
//         "SL-M",
//       ],
//       "Market": {
//         "qty": true,
//         "customPrice": false,
//         "triggerPrice": false,
//         "stopLossTrigger": false,
//         "stopLossPrice": false,
//         "targetPrice": false,
//         "trailingStopLoss": false,
//         "validity": [
//           "DAY",
//           "IOC",
//           if (Featureflag.gTD) "GTD",
//         ],
//         "Amo": true,
//         "disQty": true,
//       },
//       "Limit": {
//         "qty": true,
//         "customPrice": true,
//         "triggerPrice": false,
//         "stopLossTrigger": false,
//         "stopLossPrice": false,
//         "targetPrice": false,
//         "trailingStopLoss": false,
//         "validity": [
//           "DAY",
//           "IOC",
//           if (Featureflag.gTD) "GTD",
//         ],
//         "Amo": true,
//         "disQty": true,
//       },
//       "SL": {
//         "qty": true,
//         "customPrice": true,
//         "triggerPrice": true,
//         "stopLossTrigger": false,
//         "stopLossPrice": false,
//         "targetPrice": false,
//         "trailingStopLoss": false,
//         "validity": [
//           "DAY",
//           if (Featureflag.gTD) "GTD",
//         ],
//         "Amo": true,
//         "disQty": true,
//       },
//       "SL-M": {
//         "qty": true,
//         "customPrice": false,
//         "triggerPrice": true,
//         "stopLossTrigger": false,
//         "stopLossPrice": false,
//         "targetPrice": false,
//         "trailingStopLoss": false,
//         "validity": [
//           "DAY",
//           if (Featureflag.gTD) "GTD",
//         ],
//         "Amo": true,
//         "disQty": true,
//       },
//     },
//     "Trade": {
//       "orderTypes": [
//         "Market",
//         "Limit",
//         "SL",
//         "SL-M",
//       ],
//       "Market": {
//         "qty": true,
//         "customPrice": false,
//         "triggerPrice": false,
//         "stopLossTrigger": false,
//         "stopLossPrice": false,
//         "targetPrice": false,
//         "trailingStopLoss": false,
//         "validity": [
//           "DAY",
//           "IOC",
//           if (Featureflag.gTD) "GTD",
//         ],
//         "Amo": true,
//         "disQty": true,
//       },
//       "Limit": {
//         "qty": true,
//         "customPrice": true,
//         "triggerPrice": false,
//         "stopLossTrigger": false,
//         "stopLossPrice": false,
//         "targetPrice": false,
//         "trailingStopLoss": false,
//         "validity": [
//           "DAY",
//           "IOC",
//           if (Featureflag.gTD) "GTD",
//         ],
//         "Amo": true,
//         "disQty": true,
//       },
//       "SL": {
//         "qty": true,
//         "customPrice": true,
//         "triggerPrice": true,
//         "stopLossTrigger": false,
//         "stopLossPrice": false,
//         "targetPrice": false,
//         "trailingStopLoss": false,
//         "validity": [
//           "DAY",
//           if (Featureflag.gTD) "GTD",
//         ],
//         "Amo": true,
//         "disQty": true,
//       },
//       "SL-M": {
//         "qty": true,
//         "customPrice": false,
//         "triggerPrice": true,
//         "stopLossTrigger": false,
//         "stopLossPrice": false,
//         "targetPrice": false,
//         "trailingStopLoss": false,
//         "validity": [
//           "DAY",
//           if (Featureflag.gTD) "GTD",
//         ],
//         "Amo": true,
//         "disQty": true,
//       },
//     },
//     "CoverOrder": {
//       "orderTypes": [
//         "Market",
//         "Limit",
//         "SL",
//         "SL-M",
//       ],
//       "SL": {
//         "qty": true,
//         "customPrice": true,
//         "triggerPrice": true,
//         "stopLossTrigger": false,
//         "stopLossPrice": false,
//         "targetPrice": false,
//         "trailingStopLoss": false,
//         "validity": [
//           "DAY",
//         ],
//         "Amo": true,
//         "disQty": true,
//       },
//       "SL-M": {
//         "qty": true,
//         "customPrice": false,
//         "triggerPrice": true,
//         "stopLossTrigger": false,
//         "stopLossPrice": false,
//         "targetPrice": false,
//         "trailingStopLoss": false,
//         "validity": [
//           "DAY",
//         ],
//         "Amo": true,
//         "disQty": true,
//       },
//       "Market": {
//         "qty": true,
//         "customPrice": false,
//         "triggerPrice": false,
//         "stopLossTrigger": true,
//         "stopLossPrice": false,
//         "targetPrice": false,
//         "trailingStopLoss": false,
//         "validity": [
//           "DAY",
//         ],
//         "Amo": false,
//         "disQty": false,
//       },
//       "Limit": {
//         "qty": true,
//         "customPrice": true,
//         "triggerPrice": false,
//         "stopLossTrigger": true,
//         "stopLossPrice": false,
//         "targetPrice": false,
//         "trailingStopLoss": false,
//         "validity": [
//           "DAY",
//         ],
//         "Amo": false,
//         "disQty": false,
//       },
//     },
//     "BracketOrder": {
//       "orderTypes": [
//         "Limit",
//         "SL",
//       ],
//       "Limit": {
//         "qty": true,
//         "customPrice": true,
//         "triggerPrice": false,
//         "stopLossTrigger": false,
//         "stopLossPrice": true,
//         "targetPrice": true,
//         "trailingStopLoss": true,
//         "validity": [
//           "DAY",
//         ],
//         "Amo": false,
//         "disQty": false,
//       },
//       "SL": {
//         "qty": true,
//         "customPrice": true,
//         "triggerPrice": true,
//         "stopLossTrigger": false,
//         "stopLossPrice": true,
//         "targetPrice": true,
//         "trailingStopLoss": true,
//         "validity": [
//           "DAY",
//         ],
//         "Amo": false,
//         "disQty": false,
//       },
//     },
//   },
//   "CDS": {
//     "instrument": [
//       "FUTCUR",
//       "OPTCUR",
//     ],
//     "productTypes": [
//       "Regular",
//       if (Featureflag.coverOder) "Cover Order",
//       if (Featureflag.bracketOder) "Bracket Order",
//     ],
//     "Invest": {
//       "orderTypes": [
//         "Market",
//         "Limit",
//         "SL",
//         "SL-M",
//       ],
//       "Market": {
//         "qty": true,
//         "customPrice": false,
//         "triggerPrice": false,
//         "stopLossTrigger": false,
//         "stopLossPrice": false,
//         "targetPrice": false,
//         "trailingStopLoss": false,
//         "validity": [
//           "DAY",
//           "IOC",
//           if (Featureflag.gTD) "GTD",
//         ],
//         "Amo": true,
//         "disQty": true,
//       },
//       "Limit": {
//         "qty": true,
//         "customPrice": true,
//         "triggerPrice": false,
//         "stopLossTrigger": false,
//         "stopLossPrice": false,
//         "targetPrice": false,
//         "trailingStopLoss": false,
//         "validity": [
//           "DAY",
//           "IOC",
//           if (Featureflag.gTD) "GTD",
//         ],
//         "Amo": true,
//         "disQty": true,
//       },
//       "SL": {
//         "qty": true,
//         "customPrice": true,
//         "triggerPrice": true,
//         "stopLossTrigger": false,
//         "stopLossPrice": false,
//         "targetPrice": false,
//         "trailingStopLoss": false,
//         "validity": [
//           "DAY",
//           if (Featureflag.gTD) "GTD",
//         ],
//         "Amo": true,
//         "disQty": true,
//       },
//       "SL-M": {
//         "qty": true,
//         "customPrice": false,
//         "triggerPrice": true,
//         "stopLossTrigger": false,
//         "stopLossPrice": false,
//         "targetPrice": false,
//         "trailingStopLoss": false,
//         "validity": [
//           "DAY",
//           if (Featureflag.gTD) "GTD",
//         ],
//         "Amo": true,
//         "disQty": true,
//       },
//     },
//     "Trade": {
//       "orderTypes": [
//         "Market",
//         "Limit",
//         "SL",
//         "SL-M",
//       ],
//       "Market": {
//         "qty": true,
//         "customPrice": false,
//         "triggerPrice": false,
//         "stopLossTrigger": false,
//         "stopLossPrice": false,
//         "targetPrice": false,
//         "trailingStopLoss": false,
//         "validity": [
//           "DAY",
//           "IOC",
//           if (Featureflag.gTD) "GTD",
//         ],
//         "Amo": true,
//         "disQty": true,
//       },
//       "Limit": {
//         "qty": true,
//         "customPrice": true,
//         "triggerPrice": false,
//         "stopLossTrigger": false,
//         "stopLossPrice": false,
//         "targetPrice": false,
//         "trailingStopLoss": false,
//         "validity": [
//           "DAY",
//           "IOC",
//           if (Featureflag.gTD) "GTD",
//         ],
//         "Amo": true,
//         "disQty": true,
//       },
//       "SL": {
//         "qty": true,
//         "customPrice": true,
//         "triggerPrice": true,
//         "stopLossTrigger": false,
//         "stopLossPrice": false,
//         "targetPrice": false,
//         "trailingStopLoss": false,
//         "validity": [
//           "DAY",
//           if (Featureflag.gTD) "GTD",
//         ],
//         "Amo": true,
//         "disQty": true,
//       },
//       "SL-M": {
//         "qty": true,
//         "customPrice": false,
//         "triggerPrice": true,
//         "stopLossTrigger": false,
//         "stopLossPrice": false,
//         "targetPrice": false,
//         "trailingStopLoss": false,
//         "validity": [
//           "DAY",
//           if (Featureflag.gTD) "GTD",
//         ],
//         "Amo": true,
//         "disQty": true,
//       },
//     },
//     "CoverOrder": {
//       "orderTypes": [
//         "Market",
//         "Limit",
//         "SL",
//         "SL-M",
//       ],
//       "SL": {
//         "qty": true,
//         "customPrice": true,
//         "triggerPrice": true,
//         "stopLossTrigger": false,
//         "stopLossPrice": false,
//         "targetPrice": false,
//         "trailingStopLoss": false,
//         "validity": [
//           "DAY",
//         ],
//         "Amo": true,
//         "disQty": true,
//       },
//       "SL-M": {
//         "qty": true,
//         "customPrice": false,
//         "triggerPrice": true,
//         "stopLossTrigger": false,
//         "stopLossPrice": false,
//         "targetPrice": false,
//         "trailingStopLoss": false,
//         "validity": [
//           "DAY",
//         ],
//         "Amo": true,
//         "disQty": true,
//       },
//       "Market": {
//         "qty": true,
//         "customPrice": false,
//         "triggerPrice": false,
//         "stopLossTrigger": true,
//         "stopLossPrice": false,
//         "targetPrice": false,
//         "trailingStopLoss": false,
//         "validity": [
//           "DAY",
//         ],
//         "Amo": false,
//         "disQty": false,
//       },
//       "Limit": {
//         "qty": true,
//         "customPrice": true,
//         "triggerPrice": false,
//         "stopLossTrigger": true,
//         "stopLossPrice": false,
//         "targetPrice": false,
//         "trailingStopLoss": false,
//         "validity": [
//           "DAY",
//         ],
//         "Amo": false,
//         "disQty": false,
//       },
//     },
//     "BracketOrder": {
//       "orderTypes": [
//         "Limit",
//         "SL",
//       ],
//       "Limit": {
//         "qty": true,
//         "customPrice": true,
//         "triggerPrice": false,
//         "stopLossTrigger": false,
//         "stopLossPrice": true,
//         "targetPrice": true,
//         "trailingStopLoss": true,
//         "validity": [
//           "DAY",
//         ],
//         "Amo": false,
//         "disQty": false,
//       },
//       "SL": {
//         "qty": true,
//         "customPrice": true,
//         "triggerPrice": true,
//         "stopLossTrigger": false,
//         "stopLossPrice": true,
//         "targetPrice": true,
//         "trailingStopLoss": true,
//         "validity": [
//           "DAY",
//         ],
//         "Amo": false,
//         "disQty": false,
//       },
//     },
//   },
//   "MCX": {
//     "instrument": [
//       "FUTCOM",
//       "OPTCOM",
//     ],
//     "productTypes": [
//       "Regular",
//       if (Featureflag.coverOder) "Cover Order",
//       if (Featureflag.bracketOder) "Bracket Order",
//     ],
//     "Invest": {
//       "orderTypes": [
//         "Market",
//         "Limit",
//         "SL",
//         "SL-M",
//       ],
//       "Market": {
//         "qty": true,
//         "customPrice": false,
//         "triggerPrice": false,
//         "stopLossTrigger": false,
//         "stopLossPrice": false,
//         "targetPrice": false,
//         "trailingStopLoss": false,
//         "validity": [
//           "DAY",
//           "IOC",
//           if (Featureflag.gTD) "GTD",
//         ],
//         "Amo": true,
//         "disQty": true,
//       },
//       "Limit": {
//         "qty": true,
//         "customPrice": true,
//         "triggerPrice": false,
//         "stopLossTrigger": false,
//         "stopLossPrice": false,
//         "targetPrice": false,
//         "trailingStopLoss": false,
//         "validity": [
//           "DAY",
//           "IOC",
//           if (Featureflag.gTD) "GTD",
//         ],
//         "Amo": true,
//         "disQty": true,
//       },
//       "SL": {
//         "qty": true,
//         "customPrice": true,
//         "triggerPrice": true,
//         "stopLossTrigger": false,
//         "stopLossPrice": false,
//         "targetPrice": false,
//         "trailingStopLoss": false,
//         "validity": [
//           "DAY",
//           if (Featureflag.gTD) "GTD",
//         ],
//         "Amo": true,
//         "disQty": true,
//       },
//       "SL-M": {
//         "qty": true,
//         "customPrice": false,
//         "triggerPrice": true,
//         "stopLossTrigger": false,
//         "stopLossPrice": false,
//         "targetPrice": false,
//         "trailingStopLoss": false,
//         "validity": [
//           "DAY",
//           if (Featureflag.gTD) "GTD",
//         ],
//         "Amo": true,
//         "disQty": true,
//       },
//     },
//     "Trade": {
//       "orderTypes": [
//         "Market",
//         "Limit",
//         "SL",
//         "SL-M",
//       ],
//       "Market": {
//         "qty": true,
//         "customPrice": false,
//         "triggerPrice": false,
//         "stopLossTrigger": false,
//         "stopLossPrice": false,
//         "targetPrice": false,
//         "trailingStopLoss": false,
//         "validity": [
//           "DAY",
//           "IOC",
//           if (Featureflag.gTD) "GTD",
//         ],
//         "Amo": true,
//         "disQty": true,
//       },
//       "Limit": {
//         "qty": true,
//         "customPrice": true,
//         "triggerPrice": false,
//         "stopLossTrigger": false,
//         "stopLossPrice": false,
//         "targetPrice": false,
//         "trailingStopLoss": false,
//         "validity": [
//           "DAY",
//           "IOC",
//           if (Featureflag.gTD) "GTD",
//         ],
//         "Amo": true,
//         "disQty": true,
//       },
//       "SL": {
//         "qty": true,
//         "customPrice": true,
//         "triggerPrice": true,
//         "stopLossTrigger": false,
//         "stopLossPrice": false,
//         "targetPrice": false,
//         "trailingStopLoss": false,
//         "validity": [
//           "DAY",
//           if (Featureflag.gTD) "GTD",
//         ],
//         "Amo": true,
//         "disQty": true,
//       },
//       "SL-M": {
//         "qty": true,
//         "customPrice": false,
//         "triggerPrice": true,
//         "stopLossTrigger": false,
//         "stopLossPrice": false,
//         "targetPrice": false,
//         "trailingStopLoss": false,
//         "validity": [
//           "DAY",
//           if (Featureflag.gTD) "GTD",
//         ],
//         "Amo": true,
//         "disQty": true,
//       },
//     },
//     "CoverOrder": {
//       "orderTypes": [
//         "Market",
//         "Limit",
//         "SL",
//         "SL-M",
//       ],
//       "SL": {
//         "qty": true,
//         "customPrice": true,
//         "triggerPrice": true,
//         "stopLossTrigger": false,
//         "stopLossPrice": false,
//         "targetPrice": false,
//         "trailingStopLoss": false,
//         "validity": [
//           "DAY",
//         ],
//         "Amo": true,
//         "disQty": true,
//       },
//       "SL-M": {
//         "qty": true,
//         "customPrice": false,
//         "triggerPrice": true,
//         "stopLossTrigger": false,
//         "stopLossPrice": false,
//         "targetPrice": false,
//         "trailingStopLoss": false,
//         "validity": [
//           "DAY",
//         ],
//         "Amo": true,
//         "disQty": true,
//       },
//       "Market": {
//         "qty": true,
//         "customPrice": false,
//         "triggerPrice": false,
//         "stopLossTrigger": true,
//         "stopLossPrice": false,
//         "targetPrice": false,
//         "trailingStopLoss": false,
//         "validity": [
//           "DAY",
//         ],
//         "Amo": false,
//         "disQty": false,
//       },
//       "Limit": {
//         "qty": true,
//         "customPrice": true,
//         "triggerPrice": false,
//         "stopLossTrigger": true,
//         "stopLossPrice": false,
//         "targetPrice": false,
//         "trailingStopLoss": false,
//         "validity": [
//           "DAY",
//         ],
//         "Amo": false,
//         "disQty": false,
//       },
//     },
//     "BracketOrder": {
//       "orderTypes": [
//         "Limit",
//         "SL",
//       ],
//       "Limit": {
//         "qty": true,
//         "customPrice": true,
//         "triggerPrice": false,
//         "stopLossTrigger": false,
//         "stopLossPrice": true,
//         "targetPrice": true,
//         "trailingStopLoss": true,
//         "validity": [
//           "DAY",
//         ],
//         "Amo": false,
//         "disQty": false,
//       },
//       "SL": {
//         "qty": true,
//         "customPrice": true,
//         "triggerPrice": true,
//         "stopLossTrigger": false,
//         "stopLossPrice": true,
//         "targetPrice": true,
//         "trailingStopLoss": true,
//         "validity": [
//           "DAY",
//         ],
//         "Amo": false,
//         "disQty": false,
//       },
//     },
//   },
// };
